package fact

var List = []string{
	"No, it’s not just to make themselves look adorable. Dogs curl up in a ball when they sleep due to an age-old instinct to keep themselves warm and protect their abdomen and vital organs from predators.",
	"Smaller breeds of dogs mature faster than larger breeds.",
	"Many foot disorders in dogs are caused by long toenails.",
	"The best dog to reportedly attract a date is the Golden Retriever. The worst is the Pit Bull.",
	"The first dogs were self-domesticated wolves which, at least 12,000 years ago, became attracted to the first sites of permanent human habitation.",
	"Puppies sleep 90% of the day for their first few weeks.",
	"Seeing eye dogs pee and poo on command so that their owners can clean up after them. (The command is usually \"Get busy!\" and pups will pace back and forth until they do their business.) Male dogs are also trained to do their business without lifting their leg.",
	"Search and Rescue dog training begin as games played while puppies.",
	"Small quantities of grapes and raisins can cause renal failure in dogs. Chocolate, macadamia nuts, cooked onions, or anything with caffeine can also be harmful.",
	"Teddy Roosevelt’s dog, Pete, ripped a French ambassador’s pants off at the White House.",
	"The Labrador Retriever has been the most popular dog breed since 1991.",
	"Dogs are all direct descendants of wolves.",
	"In Roman times, mastiffs donned light armor and were sent after mounted knights.",
	"Chocolate contains a substance known as theobromine (similar to caffeine) which can kill dogs or, at the very least, make them violently ill.",
	"Police dogs can smell human bodies even when they are buried up to 3 meters in the ground.",
	"Rin Tin Tin was the first Hollywood dog star and he really signed his movie contracts – all 22 of them – with a paw-print.",
	"Hound dogs and long-nosed dogs also have a unique name for their head-type: \"Dolichocephalic.\"",
	"Most vets recommend that female dogs don’t get pregnant until the third estrus.",
	"The Beatles song \"A day in the Life\" has an extra high-pitched whistle, audible only to dogs. It was recorded by Paul McCartney for the enjoyment of his Shetland sheepdog.",
	"The Mayans and Aztecs symbolized every tenth day with the dog, and those born under this sign were believed to have outstanding leadership skills.",
	"Dogs evolved from an extinct wolf-like creature in Eurasia 40,000 years ago.",
	"Big happy \"helicopter\" tail wagging is one sign of a really nice dog",
	"A dog’s sense of smell is more than 100,000 times stronger than that of a human.",
	"Chase that tail! Dogs chase their tails for a variety of reasons: curiosity, exercise, anxiety, predatory instinct or, they might have fleas! If your dog is chasing his tail excessively, talk with your vet.",
	"Dogs have a very good sense of smell. The part of a dog’s brain that analyses smell is 40 times larger than a human’s and they can smell 1,000 to 10,000 times better than us.",
	"A dog most likely interprets a smiling person as baring their teeth, which is an act of aggression.",
	"It’s not a fever... A dog’s normal temperature is between 101 and 102.5 degrees Fahrenheit. How much do you know about dog health? Take our Doggy First Aid Quiz!",
	"Dogs belong to a biological family called the Canidae, a member of this family is called a canid. This is the origin of the adjective \"canine\" which means \"of or like a dog, relating to or characteristic of dogs\".",
	"According to a study shared by Cornell University, dogs were domesticated between 9,000 and 34,000 years ago.",
	"Although it was once illegal to keep dogs as pets in Iceland's capital city, the laws have been relaxed.",
	"Dogs curl up to keep themselves warm and protect vital organs.",
	"The Border Collie, Poodle and Golden Retriever are considered the world's smartest dog breeds.",
	"Dogs are naturally submissive to any creature with a higher pack status.",
	"Dogs have three eyelids, including one to keep their eyes moist and protected.",
	"There is a dog-shaped building in New Zealand.",
	"President Theodore Roosevelt's Bull Terrier Pete ripped the pants off French Ambassador Jules Jusserand.",
	"Express yourself. Dogs’ ears are extremely expressive. It’s no wonder! There are more than a dozen separate muscles that control a dog’s ear movements.",
	"Dogs can see in color, though they most likely see colors similar to a color-blind human. They can see better when the light is low.",
	"Dogs like sweets a lot more than cats do. While cats have around only 473 taste buds, dogs have about 1,700 taste buds. Humans have approximately 9,000.",
	"A dog’s heart beats up to 120 times per minute, or 50% faster than the average human heartbeat of 80 times per minute",
	"Puppies then take a year or more to gain the other half of their body weight.",
	"One of Michael Vick's former fighting dogs, Leo, went on to be a therapy dog who comforted dying children.",
	"This pup, Nesbit, earned over one million Delta airline miles in his life and had his own frequent flier card.",
	"Therapy dogs, who bring healing to individuals and families by visiting hospitals schools or retirement homes, differ from service dogs, who assist individuals who have disabilities.",
	"The fastest breed, the Greyhound, can run up to 44 miles per hour.",
	"Did you hear that? Sound frequency is measured in Hertz (Hz). The higher the Hertz, the higher-pitched the sound. Dogs hear best at 8,000 Hz, while humans hear best at around 2,000 Hz.",
	"The famous nickname, \"man’s best friend,\" is used in many other languages as well as English.",
	"A Border Collie named Chaser has learned the names of 1,022 toys, and can retrieve each by name.",
	"Female dogs are only ready to mate–\"in heat\"–twice a year for a total of roughly 20 days.",
	"Dogs engage in rapid-eye-movement when they sleep, and have dreams just like humans do.",
	"The average dog is as intelligent as a two-year-old child.",
	"All dogs are identical in anatomy, with 321 bones and 42 permanent teeth.",
	"Male dogs have a bone in their penis.",
	"Obesity is the top health problem among dogs.",
	"The French Bulldog is incapable of reproducing naturally.",
	"The earliest European images of dogs are found in cave paintings dating back 12,000 years ago in Spain.",
	"Max, Jake, Maggie and Molly are the most popular dog names.",
	"A dog's sense of smell is 10,000 times stronger than a human's.",
	"Mastiffs wore armor and were sent after mounted knights in Roman times.",
	"There are hundreds of breeds of dogs.",
	"A dog’s powerful sense of smell is frequently called upon to detect anything from mines and explosives to termites and bed bugs.",
	"The average dog lives 10 to 14 years.",
	"The Basenji is the world’s only barkless dog.",
	"More than half of all U.S. presidents have owned dogs.",
	"Within hours of the September 11, 2001, attack on the World Trade Center, specially trained dogs were on the scene, including German Shepherds, Labs, and even a few little Dachshunds.",
	"In ancient China, people kept warm by putting dogs up their sleeves.",
	"There are 703 breeds of purebred dogs.",
	"The origin of amputating a dog’s tail may go back to the Roman writer Lucius Columella’s (A.D. 4-70) assertion that tail docking prevented rabies.",
	"A lost Dachshund was found swallowed whole in the stomach of a giant catfish in Berlin on July 2003.",
	"At the end of the Beatles’ song \"A Day in the Life,\" a high-pitched dog whistle was recorded by Paul McCartney for his sheepdog.",
	"Dogs need a strong sense of smell because their eyesight is not as keen as a human’s.",
	"There are nearly 14,000 animal shelters and rescue groups across North America.",
	"When dogs have been doing a lot of exercise, they pant. It is not because they are out of breath like a human would be. Dogs have developed the method of losing heat by panting because sweating would not be very efficient due to all the fur.",
	"The most popular male dog names are Max and Jake. The most popular female dog names are Maggie and Molly.",
	"Watch that plate of cookies! A Dog’s sense of smell is 10,000 – 100,000 times more acute as that of humans.",
	"President Calvin Coolidge owned at least a dozen dogs.",
	"Dog’s definitely don’t see like hawks. They have very poor eyesight, but can distinguish movement 10-20 times better than humans.",
	"The name of the dog on the Cracker Jacks box is Bingo. The Taco Bell Chihuahua is a rescued dog named Gidget.",
	"The Boy Scouts and Girl Scouts both offer merit badges in dog care.",
	"Only dogs and humans have prostates.",
	"It’s been demonstrated that dogs can reduce both physical and emotional anxiety.",
	"The earliest dog fossil dates back to nearly 10,000 B.C.",
	"Dogs can smell about 1,000 times better than humans. While humans have 5 million smell-detecting cells, dogs have more than 220 million. The part of the brain that interprets smell is also four times larger in dogs than in humans.",
	"The smallest known adult dog was a Yorkshire Terrier that was only 2.5 inches at the shoulder, and weighed only 4 ounces.",
	"Dogs have twice as many muscles to move their ears as people.",
	"When \"Bobbie,\" a Collie/Shepherd mix, was accidentally abandoned on a family vacation, he traveled 2,551 miles over six months to return to his home.",
	"Irish Wolfhounds, the tallest breed, are 30 to 35 inches tall.",
	"Bingo is the name of the dog on the side of the Cracker Jack box.",
	"Dogs sweat through the pads of their feet.",
	"Dogs don’t go into menopause and will continue to go on heat indefinitely unless they are spayed.",
	"Move over Rover! 45% of dogs sleep in their owner’s bed (we’re pretty sure a large percentage also hog the blankets!)",
	"The dog was frequently depicted in Greek art, including Cerberus, the three-headed hound guarding the entrance to the underworld, and the hunting dogs which accompanied the virgin goddess of the chase, Diana.",
	"Franklin Roosevelt spent $15,000 for a destroyer to pick up his Scottie in the Aleutian Islands.",
	"In Old England, the word \"hound\" was used to refer to all types of dogs.",
	"Dogs with little human contact in the first three months typically don’t make good pets.",
	"Dog nose prints are as unique as human finger prints and can be used to identify them.",
	"The most intelligent dogs are reportedly the Border Collie and the Poodle, while the least intelligent dogs are the Afghan Hound and the Basenji.",
	"Dogs often bury bones so that they can dig them up at some moment in the future when they are hungry.",
	"The ancient Mbaya Indians of the Gran Chaco in South America believed that humans originally lived underground until dogs dug them up.",
	"Dogs were first domesticated by cavemen.",
	"Dogs judge objects first by their movement, then by their brightness, and lastly by their shape.",
	"A German Shepherd guide dog led her blind companion the entire 2,100 mile Appalachian Trail.",
	"Chocolate is poisonous to dogs because it contains theobromine.",
	"Apple and pear seeds contain arsenic, which may be deadly to dogs.",
	"National Geographic's Dr. Brady Barr measured a dog's average bite force at 320 pounds of pressure per square inch.",
	"All dogs can be traced back 40 million years ago to a weasel-like animal called the Miacis which dwelled in trees and dens. The Miacis later evolved into the Tomarctus, a direct forbear of the genus Canis, which includes the wolf and jackal as well as the dog.",
	"Puppies can sleep 18 to 20 hours a day during that rapid body growth phase.",
	"The breed of dog with the best sense of smell is the bloodhound.",
	"The Girl Scouts and Boy Scouts both offer merit badges in dog care.",
	"At about 6 inches, the Chihuahua is the shortest breed.",
	"Tiger Woods stuttered as a child and used to talk to his dog until he fell asleep in an effort to get rid of it.",
	"Wolves and dogs can mate to produce fertile offspring.",
	"Yummy! Dogs have about 1,700 taste buds. Humans have approximately 9,000 and cats have around 473.",
	"A person standing still 300 yards away is almost invisible to a dog. But a dog can easily identify its owner standing a mile away if the owner is waving his arms.",
	"Dogs with a flesh colored nose is said to have a \"Dudley Nose.\"",
	"Some dogs can smell dead bodies under water, where termites are hiding, and natural gas buried under 40 feet of dirt. They can even detect cancer that is too small to be detected by a doctor and can find lung cancer by sniffing a person’s breath.",
	"At the end of WWI, the German government trained the first guide dogs for war-blinded soldiers.",
	"Dogs cannot distinguish between red and green as these colors would appear as shades of grey to a dog.",
	"Tired puppies get cranky just like little kids. If you have a fussy puppy, try nap time.",
	"Average body temperature for a dog is 101.2 degrees.",
	"Puppies are blind, deaf and toothless when born.",
	"Dog’s don’t see in black-and-white, they have 2 color receptors, and can see yellow and blue.",
	"Puppies love games such as hide and seek! Hide, then call your pup's name so she can try to find you.",
	"Greyhounds are the fastest dogs on earth, with speeds of up to 45 miles per hour.",
	"A dog's average body temperature is 101.2 degrees.",
	"In 2001, it was estimated that there are approximately 400 million dogs in the world.",
	"In 2002 alone, more people in the U.S. were killed by dogs than by sharks in the past 100 years.",
	"The wetness of a dog's nose is essential for determining what direction a smell is coming from.",
	"With love and a little patience, dogs can learn to walk backwards, salute and bow.",
	"Conservationists have used dogs to find bumblebee hives in order to protect endangered species.",
	"It pays to be a lap dog. Three dogs (from First Class cabins!) survived the sinking of the Titanic – two Pomeranians and one Pekingese.",
	"Humans generally see better than dogs, but dogs see much better when there is low-light.",
	"Boxers are so named because of their manner of playing using their front paws.",
	"In general, smaller breeds live longer than larger breeds.",
	"Upright, stiff, rapid tail movement is not wagging or \"friendly\" but indicates a dog who's rather excited and focused.",
	"The breed Lundehune has 6 toes and can close its ears.",
	"Dogs can use their sense of smell to gauge our emotions, they can smell fear, anxiety, even sadness. This is because they can smell hormones such as adrenaline.",
	"Dogs are about as smart as a two- or three-year-old child. This means they can understand about 150-200 words, including signals and hand movements with the same meaning as words.",
	"Dogs normally have between one to sixteen or even more puppies.",
	"A dog could detect a teaspoon of sugar if you added it to an Olympic-sized swimming pool full of water.",
	"A dog can both sniff and breathe at the same time.",
	"Dogs aren't colorblind but their eyes don't have receptors for red. They see in shades of black and white and also in shades of blue and yellow.",
	"This dog, Naki'o, lost all of his legs to frostbite in Colorado, but now has four prosthetic legs and can run around like normal.",
	"The U.S. has the highest dog population in the world.",
	"A dog’s mouth exerts 150–200 pounds of pressure per square inch with some dogs exerting up to 450 pounds per square inch.",
	"Dogs with big, square heads and large ears (like the Saint Bernard) are the best at hearing subsonic sounds.",
	"Corgi is Welsh for \"dwarf dog\".",
	"Humans can detect sounds at 20,000 times per second, while dogs can sense frequencies of 30,000 times per second.",
	"President Lyndon Johnson had two beagles named Him and Her.",
	"One female dog and her female children could produce 4,372 puppies in seven years.",
	"Dogs can get jealous when their humans display affection toward someone or something else.",
	"About one-third of a dog’s brain is dedicated to smell.",
	"There are only 350 Cisky Terriers in the world, possibly making it the rarest breed.",
	"Smaller breeds mature faster than larger breeds.",
	"Puppies are sometimes rejected by their mother if they are born by cesarean and cleaned up before being given back to her.",
	"Greyhounds can reach a speed of up to 45 miles per hour.",
	"Teams of dogs compete for the fastest time without errors in Flyball races.",
	"The ancient religion Zoroastrianism includes in its religious text titled the Zend Avesta a section devoted to the care and breeding of dogs.",
	"Dogs know from which nostril a smell has entered.",
	"Dogs can be trained to detect epileptic seizures in humans.",
	"The longer a dog’s nose, the more effective it’s internal cooling system.",
	"In 1860's San Francisco, two stray dogs who were best friends became local celebrities. Their exploits were celebrated in local papers and they were granted immunity from the city's dog catchers.",
	"If your dog’s acting funny, get out the umbrella! According to a Petside.com/Associated Press poll, 72% of dog owners believe their dog can detect when stormy weather is on the way.",
	"Dogs have a ligament in the neck which allows them to conserve energy while running long distances following scent trails with their nose to the ground. Many other species have a similar ligament and it is called a Paddywhack.",
	"Male dogs know the female is in heat due to a smell emitted from the female dog.",
	"n ancient China, an emperor's last line of defense was a small Pekingese dog literally hidden up his sleeve.",
	"Why do they do that? When dogs kick after going to the bathroom, they are using the scent glands on their paws to further mark their territory.",
	"Dogs are mentioned in the Bible more than 35 times.",
	"In Egypt, a person bitten by a rabid dog was encouraged to eat the roasted liver of a dog infected with rabies to avoid contracting the disease. The tooth of a dog infected with rabies would also be put in a band tied to the arm of the person bitten. The menstrual blood of a female dog was used for hair removal, while dog genitals were used for preventing the whitening of hair.",
	"French poodles did not originate in France but in Germany (\"poodle\" comes from the German pudel or pudelhund, meaning \"splashing dog\"). Some scholars speculate the poodle’s puffs of hair evolved when hunters shaved the poodle for more efficient swimming, while leaving the pom-poms around the major joints to keep them warm.",
	"Scholars have argued over the metaphysical interpretation of Dorothy’s pooch, Toto, in the Wizard of Oz. One theory postulates that Toto represents Anubis, the dog-headed Egyptian god of death, because Toto consistently keeps Dorothy from safely returning home.",
	"Most dogs have 18 or more muscles to tilt, rotate, and move their ears.",
	"Dogs like to chew bones but cooked bones and bones that can splinter such as cooked chicken bones should not be given to dogs.",
	"Hollywood’s first and arguably best canine superstar was Rin Tin Tin, a five-day-old German Shepherd found wounded in battle in WWI France and adopted by an American soldier, Lee Duncan. He would sign his own contracts with his paw print.",
	"Even with their poor eyesight, dogs can still see better at night than humans do.",
	"A bloodhound named Tigger holds the record for the longest ears, each measuring more than 13 inches.",
	"Walt Disney's family dog -- named Sunnee -- was the inspiration behind \"Lady and the Tramp.\"",
	"More than 1 in 3 American families own a dog.",
	"In 1969, Lassie was the first animal inducted into the Animal Hall of Fame.",
	"A dog’s heart beats up to 120 times per minute, or 50% faster than the average human heartbeat of 80 times per minute.",
	"Dogs are direct descendants of wolves.",
	"Thomas Jefferson helped enact a dog tax in Virginia, because he was annoyed that dogs were killing his sheep.",
	"During the Renaissance, detailed portraits of the dog as a symbol of fidelity and loyalty appeared in mythological, allegorical, and religious art throughout Europe, including works by Leonardo da Vinci, Diego Velázquez, Jan van Eyck, and Albrecht Durer.",
	"Dogs can count up to five and can perform simple mathematical calculations.",
	"Rin Tin Tin was the first Hollywood dog star.",
	"Plato once said that \"a dog has the soul of a philosopher.\"",
	"While not the best when it comes to sight, dogs have a keen sense of hearing, and can hear sounds at 4 times the distance of humans.",
	"The Norwegian Lundehund is the only dog with six toes on each foot.",
	"Just like human fingerprints, no two dogs' nose prints are alike.",
	"More than 5,000,000 puppies are born in the U.S. every year.",
	"When dogs were evolving, bone marrow could sometimes form an important part of their diet.",
	"Dogs have no sense of time.",
	"Male dogs will raise their legs while urinating to aim higher on a tree or lamppost because they want to leave a message that they are tall and intimidating. Some wild dogs in Africa try to run up tree trunks while they are urinating to appear to be very large.",
	"The largest dog was an English Mastiff who weighed 343 pounds.",
	"The world's oldest breed, the Saluki, originated in Egypt around 329 B.C.",
	"The American Kennel Club, the most influential dog club in the United States, was founded in 1884.",
	"Here’s looking at you. Dogs have three eyelids, an upper lid, a lower lid and the third lid, called a nictitating membrane or \"haw,\" which helps keep the eye moist and protected.",
	"After the fall of Rome, human survival often became more important than breeding and training dogs. Legends of werewolves emerged during this time as abandoned dogs traveling in packs commonly roamed streets and terrified villagers.",
	"Dogs sleep for an average of 10 hours per day.",
	"Dog trainers in ancient China were held in high esteem. A great deal of dog domestication also took place in China, especially dwarfing and miniaturization.",
	"Most dogs go in heat every 6 months and estrus lasts between 7 and 18 days.",
	"As Disney's Cruella De Vil was aware, Dalmatian puppies are born pure white and develop spots as they grow older.",
	"Gidget is the name of the Taco Bell dog.",
	"Female dogs carry puppies for about nine weeks before birth.",
	"A one year old dog is as physically mature as a 15 year old human.",
	"The Berger Picard, Miniature American Shepherd and Lagotto Romagnolo are the newest dog breeds recognized by the American Kennel Club in 2015.",
	"Most dogs have 42 teeth.",
	"A German Shepherd named Orient accompanied her blind owner Bill Irwin as he became the first blind person to through-hike the 2,100-mile Appalachian Trail in 1990.",
	"Touch is the first sense the dog develops. The entire body, including the paws, is covered with touch-sensitive nerve endings.",
	"Bingo is the name of the dog on the box of Cracker Jacks.",
	"During the Middle Ages, mixed breeds of peasants’ dogs were required to wear blocks around their necks to keep them from breeding with noble hunting dogs. Purebred dogs were very expensive and hunting became the province of the rich.",
	"A dog can locate the source of a sound in 1/600 of a second and can hear sounds four times farther away than a human can.",
	"Puppies grow to half their body weight in the first four to five months!",
	"Dogs see in colors of various shades of blue and yellow.",
	"The shape of a dog’s face suggests how long it will live. Dogs with sharp, pointed faces that look more like wolves typically live longer. Dogs with very flat faces, such as bulldogs, often have shorter lives.",
	"Dogs have sweat glands in between their paws.",
	"The Saint Bernard gains its name from the \"Great St. Bernard Hospice;\" the monastery where Barry and other mountain dogs was raised by monks to rescue victims from the snowy Alps.",
	"Endal was the first dog to ride on the London Eye (the characteristic ferris wheel in London, England), and was also the first known dog to successfully use a ATM machine.",
	"Female dogs can get pregnant when their bodies undergo changes which make them receptive to male dogs. This is called being on heat or in estrus.",
	"Dogs can be taught to count and solve simple math problems.",
	"The largest breed of dog is the Irish Wolfhound.",
	"It is a myth that dogs are color blind. They can actually see in color, just not as vividly as humans. It is akin to our vision at dusk.",
	"Puppies’ eyes do not fully open until they’re about 12 days old.",
	"Newfoundlands are great swimmers because of their webbed feet.",
	"New puppies have heat sensors in their noses to help find their moms while their eyes and ears are closed.",
	"The Beagle came into prominence in the 1300s and 1400s during the days of King Henry VII of England. Elizabeth I was fond of Pocket Beagles, which were only 9\" high.",
	"Some dogs have shown remarkable ability to detect certain cancers.",
	"Thirty percent of all Dalmatians are deaf in one or both ears. Because bulldogs have extremely short muzzles, many spend their lives fighting suffocation. Because Chihuahuas have such small skulls, the flow of spinal fluid can be restricted, causing hydrocephalus, a swelling of the brain.",
	"In Croatia, scientists discovered that lampposts were falling down because a chemical in the urine of male dogs was rotting the metal.",
	"Most experts believe humans domesticated dogs before donkeys, horses, sheep, goats, cattle, cats, or chickens.",
	"The names of 77 ancient Egyptian dogs have been recorded. The names refer to color and character, such as Blackie, Ebony, Good Herdsman, Reliable, and Brave One.",
	"Pugs and other dogs with short muzzles have a peculiar head-type known as \"Brachycephalic.\"",
	"An African wolf dog known as the Basenji is the only dog in the world that cannot bark.",
	"When Lord Byron was informed that his dog was not allowed to come with him to Cambridge Trinity College, he retaliated by bringing a bear instead.",
	"An estimated 1,000,000 dogs in the U.S. have been named as the primary beneficiaries in their owner’s will.",
}
